### ISSUE TITLE
Chromium[version:69] plugin

### ISSUE THREAD

**Issue by 334943013** [lightspark/lightspark#735] opened 2021-05-08 07:22 UTC
OS: ubuntu
Platform:x86
When open an flash test website,  the plugin has loaded but didnot show anything but some GL errors:

 " ERROR: Ignoring 1 openGL errors
   ERROR: GL errors during initialization
   ERROR: Can't allocate larget texture... Aborting
"
Can anyone has some suggestion on this case ?
Thanks a lot!

**Comment by dbluelle** [comment] 2021-05-09 15:59
> OS: ubuntu
> Platform:x86

Does this mean you have compiled the 32bit version of lightspark?
> When open an flash test website, the plugin has loaded but didnot show anything but some GL errors:

Can you provide the url of the test website or upload the swf file?
> 
> " ERROR: Ignoring 1 openGL errors
> ERROR: GL errors during initialization
> ERROR: Can't allocate larget texture... Aborting
> "

Can you provide the complete log output of lightspark?
> Can anyone has some suggestion on this case ?
> Thanks a lot!

**Comment by 334943013** [comment] 2021-05-10 01:53
@dbluelle,
    I compile the source code on host x86_64 machine, same operation on armv8 platform.According the compile note .I think it's compile successfully. lightspark version is 0.8.4 and lightspark test.swf can play the flash.

But if we use chromium browser x86_64 or arm platform, it failed.
test website:www.ultarsounds.com


Whole log info:

INFO: Lightspark version 0.8.4 Copyright 2009-2013 Alessandro Pignotti and others
INFO: PPP_getInterface:PPP_Instance;1.1
INFO: PPP_getInterface:PPP_Instance;1.1
INFO: Instance_DidCreate:1997820037
ERROR: pluginworker
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
INFO: RenderThread this=0x33e6d130
INFO: Creating input thread
INFO: param:src test.swf
INFO: param:quality high
INFO: param:pluginspage http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash
INFO: param:type application/x-shockwave-flash
INFO: param:width 550
INFO: param:height 200
[5407:5444:0510/092026.139779:ERROR:gles2_cmd_decoder.cc(2653)] [GroupMarkerNotSet(crbug.com/242999)!:5090594C7F000000]GL ERROR :GL_INVALID_ENUM : BackFramebuffer::Create: <- error from previous GL command
INFO: Instance_DidChangeView: create:550 200
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
ERROR: GL error 1280
ERROR: Ignoring 1 openGL errors
ERROR: GL errors during initialization
INFO: mainclip url:http://www.ultrasounds.com/test.swf
INFO: zlib compressed SWF file: Version 6
INFO: download finished:test.swf 1242
INFO: FrameRate 12
INFO: Creating VM
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
NOT_IMPLEMENTED: Unsupported tag type 62
NOT_IMPLEMENTED: Unimplemented Tag 62
ERROR: state.next_FP >= getFramesLoaded:1 1 [object MovieClip](0x33e53e20 / 1)  4294967295
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
ERROR: Ignoring 1 openGL errors
ERROR: GL errors during initialization
ERROR: Ignoring 1 openGL errors
INFO: FPS: 1 0
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
INFO: FPS: 12 0
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors
ERROR: Ignoring 1 openGL errors

It seems  that lightspark already works but the opengl init has some errors.
At same time, lightspark can plays local swf file without chromium brower.

**Comment by dbluelle** [comment] 2021-05-16 15:36
Sorry, but I couldn't reproduce your problem. It seems that chromium is unable to create the openGL context, I don't know why.

**Comment by 334943013** [comment] 2021-05-21 01:36
@dbluelle：
   I used mesa to simulate opengles2 , there is no error on opengl context init errors.
And more the render thread continues to render according to log:INFO: FPS: 11 0...
but there still no flash showing in chromium

LOG:
----------------------------------------

INFO: Lightspark version 0.8.4 Copyright 2009-2013 Alessandro Pignotti and others
INFO: PPP_getInterface:PPP_Instance;1.1
INFO: PPP_getInterface:PPP_Instance;1.1
INFO: Instance_DidCreate:583645477
ERROR: pluginworker
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
INFO: RenderThread this=0x2c3cab30
INFO: Creating input thread
INFO: param:src test.swf
INFO: param:quality high
INFO: param:pluginspage http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash
INFO: param:type application/x-shockwave-flash
INFO: param:width 550
INFO: param:height 200
INFO: Instance_DidChangeView: create:550 200
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: ---------loadshader-------1
INFO: ---------driverInfo-------OpenGL Vendor=VMware, Inc. Version=OpenGL ES 2.0 Chromium Renderer=llvmpipe (LLVM 6.0, 128 bits) GLSL=OpenGL ES GLSL ES 1.0 Chromium
INFO: ---------tex 2------8
INFO: mainclip url:http://www.ultrasounds.com/test.swf
INFO: download finished:test.swf 1242
INFO: zlib compressed SWF file: Version 6
INFO: FrameRate 12
INFO: Creating VM
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
NOT_IMPLEMENTED: Unsupported tag type 62
NOT_IMPLEMENTED: Unimplemented Tag 62
ERROR: state.next_FP >= getFramesLoaded:1 1 [object MovieClip](0x2c3b1800 / 1)  4294967295
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: ---------driverInfo-------OpenGL Vendor=VMware, Inc. Version=OpenGL ES 2.0 Chromium Renderer=llvmpipe (LLVM 6.0, 128 bits) GLSL=OpenGL ES GLSL ES 1.0 Chromium

INFO: FPS: 1 0
INFO: FPS: 8 0
INFO: FPS: 11 0
INFO: FPS: 12 0
INFO: FPS: 11 0
INFO: FPS: 11 0
INFO: FPS: 11 0
.....
---------------------------------------
Eger to your rely, thanks

**Comment by dbluelle** [comment] 2021-05-24 15:02
I've committed some changes that might help with this issue.
However I still get other openGL errors when using the PPAPI plugin, which I could not yet resolve.

**Comment by huwdp** [comment] 2021-11-01 17:49
Closing this ticket as Chrome or Chromium no longer support plugins such as Lightspark. You could carry on using Chrome 69 but it would be better to use up-to-date alternatives listed [here](https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser).

**Closed by huwdp** 2021-11-01 17:49 UTC
