### ISSUE TITLE
Lightspark sometimes does not close when the close button is pressed

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#514] opened 2020-06-19 04:26 UTC
Here is one example: [qwop.zip](https://github.com/lightspark/lightspark/files/4802427/qwop.zip)

It looks like sigterm causes the game to freeze, nothing more. The only way to close it is with a sigkill.

This is using lightspark compiled from master, which right now is commit dd5f1083dbaa2f7866f0a79408cf7ec0237f5af3.

**Comment by dbluelle** [comment] 2020-06-21 06:00
Unfortunately I couldn't reproduce this with your swf file.
I also experience this behaviour sometimes, however I wasn't able to find an example where the freezes are reproducible, so it's very hard to debug...

**Comment by huwdp** [comment] 2020-06-22 16:09
I can't replicate this issue too although I have had issues with closing the window a few times with other swf files at what seems like random times

**Comment by eiglow** [comment] 2020-06-29 02:30
[skullkid.zip](https://github.com/lightspark/lightspark/files/4843439/skullkid.zip)
With this swf, after clicking Play, then Play again, and then attempting to close it, it hangs for a second until the loop of music ends. Perhaps whatever's causing that might be the root of the problem?

**Comment by huwdp** [comment] 2020-07-13 17:45
Something I did find odd is that when closing Lightspark with a working swf, the systems sends a LS_USEREVENT_QUIT event and everything closes properly. With this file I have included, it does not. The problem with this file is 100% reproducible.

**Closed** 2020-07-18 18:20 UTC
