### ISSUE TITLE
Regression on bcb769a9a8b72c4bb623d25705738e395bd4b35a

### ISSUE THREAD

**Issue by JousterL** [lightspark/lightspark#879] opened 2021-12-31 22:02 UTC
## In order to help us understand your issue, please follow the guide below

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---
#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

http://d.furaffinity.net/art/jousterl/1405946010/1405946010.jousterl_1405925576.jasonafex_scappo_slime_girl_jasonafex.swf (NSFW)

#### Provide the complete set of instructions required to reproduce the problem:

1. Compile commit 7c71a588db17c06e179f25717ac0f98c56c487a4
2. Run the flash in Lightspark
3. Observe functional flash
4. Compile commit bcb769a9a8b72c4bb623d25705738e395bd4b35a or subsequent
5. Run the flash in Lightspark
6. Observe "We're sorry, Lightspark encountered a yet unsupported Flash file."

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1288-gd0664ecd Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: *<Ubuntu 21.10>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---
[log.txt](https://github.com/lightspark/lightspark/files/7797115/log.txt)

**Comment by dbluelle** [comment] 2022-01-02 16:18
I couldn't reproduce the issue with the current master.
However I got another exception when moving the mouse over the main menu, which is now fixed.
Please check again if your issue still occurs.

**Comment by JousterL** [comment] 2022-01-02 19:44
It's intermittent with the latest build; I realized there were two issues on the build I was testing, and you have resolved the main menu exception. However, I ran it ten times and it crashed out on run 1, 8, and 10. 

It looks like something isn't always getting initialized properly as it always occurs on frame1() of the MainTimeline object. Here's a comparison of two -l 4 logs for the relevant section:
![image](https://user-images.githubusercontent.com/439681/147887536-65c33c22-a69f-4778-afe3-034f0d773dcb.png)

Initially I thought it was a problem with the NaNd property, but it looks instead like it's a problem with flash.display::MovieClip not being initialized properly? I'll keep poking around in GDB and see if I can identify the state in error condition.

**Comment by JousterL** [comment] 2022-01-07 23:45
Everything about this feels like a race condition where it attempts to call the getBounds property on the flash.display::MovieClip before another thread has a chance to initialize it. When I un-commented the log line at line 109 for abc_interpreter.cpp it became more difficult to induce the crash (once every 15 or so launches), likely because logging all the stack call positions on context slowed the program down.

I have to admit that I'm pretty far out of my understanding, as this appears to be executing functions defined on the context against variables defined in the context, and GDB doesn't like parsing a lot of what's there. The best I was able to get was this:
![image](https://user-images.githubusercontent.com/439681/148620896-a20d0101-83b3-438b-959c-5e9c6b21186e.png)

The object getBounds is attempting to read is a memory location when it works, and 0x40 when it's not. But since this is a virtual function, I can't run up the backtrace to figure out why it's not initialized. I'm hoping you might have more insight.

**Comment by JousterL** [comment] 2022-01-10 20:39
Additional details: The more cores I have in the VM, the less likely I am to experience the error. With 1 or 2 cores it's 40-50% of the time, with 4 cores it's thus far been impossible to replicate (50+ launches).

Also on a hunch, I recompiled it in Release rather than Debug mode, and am not seeing the error regardless of number of cores. It appears to be limited to the Debug build. Apologies that I didn't check this sooner.

**Comment by JousterL** [comment] 2022-01-24 15:49
Out of curiosity, is there a function that can be called to rebuild/reinitialize the loading process? It's kludgy, but I'm thinking something like the following psuedocode would at least ameliorate whatever race condition is going on here:

`if Property isNull() {
     reinitialize();
}`

Since the callProperty_lll is only called once in the entire process, and most of the time (>80%) it doesn't fail, it seems like a reload catch would solve for this.

**Comment by dbluelle** [comment] 2022-01-24 18:33
Even if we had such a thing I don't think that would help much as it does not fix the source of the problem.
I think it's a multithreading issue, so that the frame1() function is executed before the elements on the first frame of the main timeline are completely constructed.
However, the good news is that I found a way to reproduce the issue quite reliably:
Run lightspark on just one core (using the  taskset command ) triggers the issue most of the time.

**Closed** 2022-01-25 17:52 UTC

**Comment by JousterL** [comment] 2022-01-25 18:03
Great! Thank you very much, I can confirm this has solved the issue!
