### ISSUE TITLE
can't run lightspark any longer using gui

### ISSUE THREAD

**Issue by Croworbit** [lightspark/lightspark#1142] opened 2024-11-16 18:28 UTC
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ x] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
Lightspark version 0.8.7 Copyright 2009-2013
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ x] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x ] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [x ] I ran `lightspark -l 4` on the command line 

---

### Description of your issue
built the latest using the source code, and tried to run any game using the gui and it did not work, I was trying to get video for my previous issue, and no swf worked  until I ran it with `lightspark -l 4`

**Comment by dbluelle** [comment] 2024-11-20 16:45
Please start lightspark with -l 2 and upload the output here.

**Comment by dbluelle** [comment] 2024-11-21 10:26
It looks like a regression when parsing filters.
Please upload the swf file you are trying to start.

I've committed a fix for some issues with filters last week, maybe your build is older than that: https://github.com/lightspark/lightspark/commit/aa35b23152b75d2df626e6f129f79d6a07995e68

**Comment by Croworbit** [comment] 2024-11-21 14:32
the swf file I'm using is the same one from my other issues
https://echoesgame.com/play.html

I'll test on latest again later, but it was very recent 

what makes `lightspark -l 4` work over just running normally?

**Comment by dbluelle** [comment] 2024-11-21 16:22
Normally -l 4 should only make everything run slower due to writing all the log output.
That may have an impact on multithreading stuff, but it shouldn't have the effect you describe.

I've tested with the echoes swf, but unfortunately I couldn't reproduce the issue.

**Comment by Croworbit** [comment] 2024-11-23 00:12
I tried this again using the latest, after building, clicking the file to open the gui opens as before but opening any game on my list closes the window
running the command line `lightspark` does not work, neither `lightspark -l 2`, but `lightspark -l 4` does keep the game open and it is playable

I don't remember the last time it worked without `-l 4` but it was for sure working in july, but it was okay for a while after

**Comment by Croworbit** [comment] 2024-11-23 00:47
okay, update on this
I went to go download old code from that time, but its been replaced since on the releases tab, so I checked my files, I have a september version sept 29

it was on my 'old ls' folder
so it had trouble compiling, apparently the path cannot have parenthesis or it errors and stops, and also it also does not like spaces on the path, or the 'ls' part of 'old ls' is special (I clearly have no idea what I'm doing)
I almost gave up because I can't read errors that well, but it built and yes, the window stays open if I just click on the file and run the game, so that hopefully narrows it

**Comment by Croworbit** [comment] 2024-11-25 22:19
it gets weirder. 
the old version
- works when just clicking to open 
- crashes when running with `lightspark -l 2`
- works when running with `lightspark -l 4`
- crashes when skipping launcher and running directly

the new version
- crashes when just clicking to open
- crashes when running with `lightspark -l 2`
- works running with `lightspark -l 4`
- crashes when skipping launcher and running directly

here is the log for the old version
[log-2.txt](https://github.com/user-attachments/files/17909521/log-2.txt)

**Comment by dbluelle** [comment] 2024-11-29 20:12
It seems that the crash occurs inside the loaded swf for the adviewer:
http://server.cpmstar.com/adviewas3.swf?poolid=1052&subpoolid=44
I don't get that crash, so maybe my version of the adviewer is different than yours (although it seems to have the same size)?

One other thing:
Did you delete your build folder before building the new version?
If not, then maybe something wasn't properly rebuild...

**Comment by Croworbit** [comment] 2024-11-29 21:34
is that build folder the same one that I'm creating before I compile? do I delete every build folder I have from lightspark versions?

**Comment by dbluelle** [comment] 2024-11-29 22:22
If you are following the instructions in the README, it's the "build" folder where everything is compiled into.
So clearing that ensures that everything is compiled again.
It shouldn't be necessary to clear that as during building it is automatically checked which files have changed and only those are compiled again (speeds up compilation).
But in your case clearing that folder may be better to make sure everything is really rebuilt, so we can exclude that as the source of your problem.

**Comment by Croworbit** [comment] 2024-11-30 01:59
that did seem to change something

I removed every 'build' folder each time I went to test a different version 

so the results are 

each method actually works on the old version just fine after all

the new version crashes as described earlier


I guess I can't have 2 lighspark versions built at once?

**Comment by dbluelle** [comment] 2024-11-30 14:23
You can always use another name for the build directory and build in that directory:
```cd lightspark
mkdir build_new
cd build_new
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
```
or just copy the downloaded sourcecode in another directory and build from there.

I've just committed a fix for some possible crashes.
I doubt it will help in your case, but please try and post the -l 2 log again.

**Comment by Croworbit** [comment] 2024-11-30 16:37
here is the log 
[log-3.txt](https://github.com/user-attachments/files/17966087/log-3.txt)

**Comment by dbluelle** [comment] 2024-11-30 17:13
It just occured to me that maybe I'm just using a different version of the echoes main swf file than you.
Mine is called echoes_act1_12_secure.swf, is 34.073.753 bytes big and has 17th of july 2019 as modification date.
Maybe you can upload your version here?

**Comment by Croworbit** [comment] 2024-11-30 17:23
I would, but there is a limit on the size of uploads to github.
looking at the size of the swf I'm using, its the same as yours

I'll try to find the site I got this specific one from

**Comment by Croworbit** [comment] 2024-11-30 17:27
I think I found it here:
https://archive.org/details/echoes-operation-stranglehold-flash-game/

**Comment by dbluelle** [comment] 2024-11-30 20:20
OK, that's the same one I'm using.
I'm slowly running out of ideas...
Please upload a -l 4 log where it works. It doesn't have to be long, just enough so that something is displayed.

**Comment by Croworbit** [comment] 2024-11-30 21:05
here is the log... despite only being open for a few seconds, this log is very large
[log-4.txt](https://github.com/user-attachments/files/17966892/log-4.txt)

**Comment by dbluelle** [comment] 2024-12-01 07:44
Hmm, the log looks all right. 
Please upload a -l 4 log of the _new_ version. If it gets too large, you can zip the log and upload that.
Please clear your build directory (or use an empty one) and upload the output of the `cmake -DCMAKE_BUILD_TYPE=Release ..` command.
What Linux Distribution are you using?

**Comment by Croworbit** [comment] 2024-12-01 14:44
here is the log of the latest version of lightspark 
[log-5.txt](https://github.com/user-attachments/files/17969282/log-5.txt)

here is the output of that command 
[log-6.txt](https://github.com/user-attachments/files/17969284/log-6.txt)

I use Mint

**Comment by Croworbit** [comment] 2024-12-03 10:42
it might be LMDE
there isn't a special reason for my gcc version, I think

to be honest after all this, my install seems to just be cursed, this could be a me problem
if there is nothing else for me to try I can close this issue after some time

**Comment by dbluelle** [comment] 2024-12-03 18:05
Good News!
I reproduced the issue with a virtual machine running LMDE 6.
I've just committed the fix and now it runs in the VM.
It's interesting that it only occured in that specific distribution, that crash could/should have happened almost everywhere...
OK, so please test it and if it works for you we can close this issue.

**Comment by Croworbit** [comment] 2024-12-03 21:16
I just tested it
it works! actually, all the other methods to open the game work too with this version

**Comment by Croworbit** [comment] 2024-12-03 21:17
thank you
what was the problem that caused this?
thanks for looking into this and providing a quick fix

**Comment by dbluelle** [comment] 2024-12-04 15:42
The problem was that we checked for an uninitialized boolean value (which was a bug I introduced...).
Most compilers seem to initialize it to false, but for some reason the compiler on LMDE didn't.
So this was a good find as we were relying on undefined behaviour of the compiler.

**Closed by dbluelle** 2024-12-04 15:42 UTC
