### ISSUE TITLE
Audio Crash on Arch/EndeavourOS

### ISSUE THREAD

**Issue by poudink** [lightspark/lightspark#931] opened 2022-04-10 17:14 UTC
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### Provide the complete set of instructions required to reproduce the problem:

1. Install lightspark-git AUR package
2. Launch any SWF file with audio
3. Lightspark crashes when trying to play audio

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [X] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``: 

```
INFO: Lightspark version 0.8.5-1466-ge76a32da Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: *EndeavourOS KDE Plasma*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue
Since my switch from Fedora 35 to the Arch-based EndeavourOS, Lightspark has started crashing every time it tries to play audio. This happens with ever SWF file I tried. No clue why. Here's some logs (-l4) (all starting from the point Lightspark starts trying to play audio, nothing out of the ordinary happens before that):
Super Mario 63 (https://github.com/lightspark/lightspark/files/8266408/Super.Mario.63.zip):
```
[mp3 @ 0x7f1b542c9ec0] Skipping 2 bytes of junk at 0.
INFO: AUDIO DEC: Audio sample rate 22050
INFO: AUDIO DEC: Audio channels 1
Erreur de segmentation (core dumped)
```
Backtrace: [Super Mario 63.log](https://github.com/lightspark/lightspark/files/8459536/Super.Mario.63.log)
Raze (https://github.com/lightspark/lightspark/files/6780472/Raze.zip):
```
[mp3 @ 0x7f2c4874adc0] Skipping 2 bytes of junk at 0.
INFO: AUDIO DEC: Audio sample rate 11000
INFO: AUDIO DEC: Audio channels 1
Erreur de segmentation (core dumped)
```
Backtrace: [Raze.log](https://github.com/lightspark/lightspark/files/8459542/Raze.log)
Excuse the French, "Erreur de segmentation" simply means "Segmentation fault".

**Comment by dbluelle** [comment] 2022-04-10 17:28
I just committed some fixes for audio and multithreading that may fix this, too.

**Comment by poudink** [comment] 2022-04-10 22:22
doesn't look like that worked, but I think the logs are looking slightly different now (could just be random):
Super Mario 63:
```
INFO: AUDIO DEC: Audio sample rate 22050
TRACE: Reading tag type: 26 at byte 3635358 with length 10 bytes
TRACE: PlaceObject2
INFO: AUDIO DEC: Audio channels 1
Erreur de segmentation (core dumped)
```
[bt.log](https://github.com/lightspark/lightspark/files/8460034/bt.log)
Raze:
```
INFO: AUDIO DEC: Audio sample rate 11025
INFO: AUDIO DEC: Audio channels 1
CALLS: Method trait: [ns:] EnterFrame #1134
CALLS: Method trait: [privns:] hitNearbyEnemies #1135
CALLS: Finished script init for script 151
TRACE: Placing ID 1028
CALLS: Running script init for script 152
INFO: AUDIO DEC: Audio sample rate 11000
INFO: AUDIO DEC: Audio channels 1
CALLS: Method trait: [ns:] EnterFrame #1139
CALLS: Method trait: [privns:] hitNearbyEnemies #1140
CALLS: Finished script init for script 152
Erreur de segmentation (core dumped)
```
[bt.log](https://github.com/lightspark/lightspark/files/8460035/bt.log)

**Comment by dbluelle** [comment] 2022-04-11 13:36
Sorry, but I can't reproduce the crashes.
It seems like lightspark is crashing somewhere inside ffmpeg...
Did you build lightspark from an empty build directory?  ffmpeg is sometimes not properly configured when using an existing build directory after ffmpeg was updated to a new version.
Perhaps try a debug build, that may produce a more readable backtrace (be aware that the log file gets very large if a debug build is run with -l 4).

**Comment by poudink** [comment] 2022-04-11 17:23
Alright, here's some logs from a debug build (using an empty directory). [SM63.zip](https://github.com/lightspark/lightspark/files/8466349/SM63.zip)
Also, I just noticed something with cmake:
```
cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test GCC_IS_4_6
-- Performing Test GCC_IS_4_6 - Success
-- Gnash not found
-- The ASM-NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.12") 
-- Found Freetype: /usr/lib/libfreetype.so  
-- Found JPEG: /usr/lib/libjpeg.so (found version "80") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.37") 
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found GLEW: /usr/lib/libGLEW.so  
-- Checking for module 'liblzma'
--   Found liblzma, version 5.2.5
-- Checking for modules 'cairo;pangocairo'
--   Found cairo, version 1.17.6
--   Found pangocairo, version 1.50.6
-- Checking for modules 'libavcodec;libavutil;libavformat'
--   Found libavcodec, version 59.18.100
--   Found libavutil, version 57.17.100
--   Found libavformat, version 59.16.100
-- Checking for module 'libswresample'
--   Found libswresample, version 4.3.100
-- Looking for avcodec_decode_video2
-- Looking for avcodec_decode_video2 - not found
-- Looking for avcodec_decode_audio3
-- Looking for avcodec_decode_audio3 - not found
-- Looking for avcodec_decode_audio4
-- Looking for avcodec_decode_audio4 - not found
-- Looking for avio_alloc_context
-- Looking for avio_alloc_context - found
-- Looking for avcodec_alloc_context3
-- Looking for avcodec_alloc_context3 - found
-- Looking for avcodec_open2
-- Looking for avcodec_open2 - found
-- Looking for avformat_close_input
-- Looking for avformat_close_input - found
-- Looking for avformat_find_stream_info
-- Looking for avformat_find_stream_info - found
-- Looking for av_frame_alloc
-- Looking for av_frame_alloc - found
-- Looking for av_frame_unref
-- Looking for av_frame_unref - found
-- Looking for av_packet_unref
-- Looking for av_packet_unref - found
-- Looking for avcodec_send_packet
-- Looking for avcodec_send_packet - found
-- Looking for avcodec_receive_frame
-- Looking for avcodec_receive_frame - found
-- Looking for av_frame_get_sample_rate
-- Looking for av_frame_get_sample_rate - not found
-- Performing Test HAVE_AVCODECID
-- Performing Test HAVE_AVCODECID - Success
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.72.0
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.20
-- Checking for module 'SDL2_mixer'
--   Found SDL2_mixer, version 2.0.4
-- Checking for module 'libcurl'
--   Found libcurl, version 7.82.0
-- Checking for module 'librtmp'
--   Found librtmp, version v2.4
-- Looking for C++ include atomic
-- Looking for C++ include atomic - found
-- Checking for module 'x11'
--   Found x11, version 1.7.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/poudink/lightspark/build
```
Seems like there are a few audio related things that it can't find, tho it doesn't seem to have any issue with that. I know I have ffmpeg installed.

**Comment by dbluelle** [comment] 2022-04-15 06:02
Hmm, the cmake output looks ok, I have the same versions of the ffmpeg libraries. 
The "not found" messages are for older ffmpeg versions where the API was different.

**Closed** 2022-04-15 07:23 UTC
